service: sls-aurora-autoscale-add-tags

# frameworkVersion: '3'

provider:
  name: aws
  stage: prd
  runtime: python3.8
  region: ap-northeast-1
  timeout: 300
  memorySize: 128
  logRetentionInDays: 60
  iam:
    role:
      statements:
       - Effect: "Allow"
         Action: 
           - "rds:AddTagsToResource"
           - "rds:ListTagsForResource"
         Resource: "*"

functions:
  sls-aurora-autoscale-add-tags:
    name: sls-aurora-autoscale-add-tags
    handler: handler.lambda_handler
    events:
      - cloudwatchEvent:
          name: sls_aurora-autoscale-add-tags
          event:
            source:
              - 'aws.rds'
            detail-type:
              - 'RDS DB Instance Event'
            detail:
              Message:
                - 'DB instance created'
